# Generated by Django 4.2.8 on 2023-12-09 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ator',
                'verbose_name_plural': 'Atores',
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=200)),
                ('capacidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Diretor',
                'verbose_name_plural': 'Diretores',
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('duracao', models.IntegerField()),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes', to='core.diretor')),
            ],
        ),
        migrations.CreateModel(
            name='FilmeEstrangeiro',
            fields=[
                ('filme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.filme')),
                ('titulo_ingles', models.CharField(max_length=200)),
                ('pais_origem', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Filme Estrangeiro',
                'verbose_name_plural': 'Filmes Estrangeiros',
            },
            bases=('core.filme',),
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('publico', models.BooleanField(default=False)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='core.cinema')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='core.filme')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
            },
        ),
        migrations.CreateModel(
            name='Atuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atuacoes', to='core.ator')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atuacoes', to='core.filme')),
            ],
            options={
                'verbose_name': 'Atuação',
                'verbose_name_plural': 'Atuações',
            },
        ),
    ]
